* IESDP file formats
https://gibberlings3.github.io/iesdp/file_formats/
https://gibberlings3.github.io/iesdp/file_formats/general.htm

* Use Gloss for the byte data parsing
https://github.com/clj-commons/gloss/wiki/Introduction

* Clojure directory/file watchers
Try out these options
https://github.com/derekchiang/Clojure-Watch
https://github.com/juxt/dirwatch

* It looks like NI accommodates extra bytes on the end of a record
This usually seems to be due to misindexing in the header (for
instance, sw1h03.itm - Kondar - I end up with just enough bytes at the
end of the file for one more item effect).

NI highlights this in gray instead of the usual green.

Similarly, resref entries are pure garbage on some (maybe a mod uses
that memory area for some special purpose) - it breaks the parser
unless I take simple bytes - in NI they just get zeroed out to the
null bytes in their hex editor.

* Import timing on dialog file
It's possible to write to the csv in ~50 seconds, and import via:

#+begin_src
echo '.import --csv --skip 1 /tmp/dialog1.csv dialog' | sqlite3 ./override.db
#+end_src

in around 10 - making the total process take 60s instead of 120s,
however this wouldn't really be cross platform compatible in the same
way that the JVM is.

* Clojure refreshers
Building a clojure web app using ring jetty
https://otee.dev/2022/01/25/clojure-backend-using-ring-jetty-compojure.html

Building a clojurescript app / spa
https://medium.com/codex/creating-a-clojurescript-spa-for-the-first-time-pt-1-d3012c42e622

Setting up figwheel (used this instead of second link)
https://figwheel.org/#quick-usage

* Controlling alternate log file
-Dlogback.configurationFile=/path/to/config.xml
